force-app/main/default/objects/CallList__c/CallList__c.object-meta.xml
<CustomObject>
    <description>Capture a list of Leads assigned to specified owner to be called in specific order/priority</description>
    <label>Call List</label>
    <nameField>
        <label>Call List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CallListMember__c/CallListMember__c.object-meta.xml
<CustomObject>
    <description>Used to determine a specific Lead for a specific Call List with specified Status and Order</description>
    <label>Call List Member</label>
    <nameField>
        <label>Call List Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CallListMember__c/fields/CallList__c.field-meta.xml
<CustomField>
    <fullName>CallList__c</fullName>
    <description>The related Call List this member is for</description>
    <label>Call List</label>
    <referenceTo>CallList__c</referenceTo>
    <relationshipLabel>Call List Members</relationshipLabel>
    <relationshipName>Call_List_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CallListMember__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order number this Lead should be called.  Lower number means the Lead should be called first</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CallListQueryAction.cls
public without sharing class CallListQueryAction {
	@InvocableMethod
    public static List<Integer> getNextOrderNumbers(List<Id> ids) {
        List<Integer> orderNumbers = new List<Integer>();
        AggregateResult[] groupedResults = [SELECT CallList__c, MAX(Order__c) FROM CallListMember__c WHERE CallList__c in : ids GROUP BY CallList__c];
        for(AggregateResult ar : groupedResults){
            orderNumbers.add(Integer.valueOf(ar.get('expr0')) + 1);
        }
	
	// return the order numbers
        return orderNumbers;
    }
}