force-app/main/default/objects/CallList__c/CallList__c.object-meta.xml
<CustomObject>
    <description>Capture a list of Leads assigned to specified owner to be called in specific order/priority</description>
    <label>Call List</label>
    <nameField>
        <label>Call List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CallListMember__c/CallListMember__c.object-meta.xml
<CustomObject>
    <description>Used to determine a specific Lead for a specific Call List with specified Status and Order</description>
    <label>Call List Member</label>
    <nameField>
        <label>Call List Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CallListMember__c/fields/CallList__c.field-meta.xml
<CustomField>
    <fullName>CallList__c</fullName>
    <description>The related Call List this member is for</description>
    <label>Call List</label>
    <referenceTo>CallList__c</referenceTo>
    <relationshipLabel>Call List Members</relationshipLabel>
    <relationshipName>Call_List_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CallListMember__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Lead record to be called</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Call List Members</relationshipLabel>
    <relationshipName>Call_List_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CallListMember__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order number this Lead should be called.  Lower number means the Lead should be called first</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CallListMember__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Called</fullName>
                <default>true</default>
                <label>Not Called</label>
            </value>
            <value>
                <fullName>Called</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CallListQueryActionTest.cls
@isTest
private class CallListQueryActionTest {
    @isTest
    static void testGetLastOrderNumbers() {
        // create test Leads
        List<Lead> testLeads = new List<Lead>();
        testLeads.add(New Lead(FirstName = 'test1', LastName = 'test1', Company = 'Company1', Phone = '0290453311', MobilePhone = '0411111111'));
        testLeads.add(New Lead(FirstName = 'test2', LastName = 'test2', Company = 'Company2', Phone = '0290453312', MobilePhone = '0411111122'));
    	insert testLeads;
        
    	// create test Call List
    	CallList__c testCallList = new CallList__c(Name = 'Test Call List');
        insert testCallList;
        
        // create test Call List Member
        Lead lead1 = [SELECT Id FROM Lead WHERE FirstName = 'test1'];
        Lead lead2 = [SELECT Id FROM Lead WHERE FirstName = 'test2'];
        
        List<CallListMember__c> clms = new List<CallListMember__c>();
        clms.add(new CallListMember__c(CallList__c = testCallList.Id, Lead__c = lead1.Id, Status__c = 'Not Called', Order__c = 1));
        clms.add(new CallListMember__c(CallList__c = testCallList.Id, Lead__c = lead1.Id, Status__c = 'Not Called', Order__c = 12));
        insert clms;
        
        Test.startTest();
        List<Id> ids = new List<Id>{testCallList.Id};
        List<Integer> orderNumbers = CallListQueryAction.getNextOrderNumbers(ids);
        Test.stopTest();
        
        System.assertEquals(13, orderNumbers[0], 'Next order number should be 13'); 
    }
}